Repository LG-Uplus-Movie-SNS-PICKY/PICKY-FE, pull requests merged in 2024-12, with the labels that each got.

#62 [FIX] 1차 QA 진행상황 반영
  package.json
  src/assets/icons/add_circle_media.svg
  src/assets/images/logo.png
  src/components/emoji-render/index.tsx
  src/components/genre/index.styles.tsx
  src/components/genre/index.tsx
  src/components/layout/index.tsx
  src/components/seo/index.tsx
  src/constants/genre/index.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/handlers/movie/genre/index.ts
  src/pages/main/components/genres-movie/index.styles.tsx
  src/pages/main/components/genres-movie/index.tsx
  src/pages/main/components/recommend-slider/index.tsx
  src/pages/main/index.tsx
  src/pages/movie-detail/index.tsx
  src/pages/movie-detail/reviews/index.tsx
  src/pages/search/index.tsx
  src/pages/signup/components/favorite-genre/index.tsx
  src/recoil/selectors/genresSelector.tsx
  src/routers/Router.tsx
  src/stories/file-input/components/basic/index.styles.tsx
  src/stories/file-input/components/basic/index.tsx
  src/stories/file-input/components/media/index.styles.tsx
  src/stories/file-input/components/media/index.tsx
  src/stories/file-input/components/media/slider/index.styles.tsx
  src/stories/file-input/components/media/slider/index.tsx
  src/stories/file-input/index.styles.tsx
  src/stories/file-input/index.tsx
  src/stories/movie-log/MovieLog.stories.tsx
  src/stories/movie-log/index.styles.tsx
  src/stories/movie-log/index.tsx
  src/types/emoji-toolkit.d.ts
  yarn.lock
Labels: 🐞 BugFix

#64 [FEAT] 토스트메세지, 모달창 스토리북 추가 (#60)
  src/stories/modal/Modal.stories.ts
  src/stories/modal/index.styles.tsx
  src/stories/modal/index.tsx
  src/stories/toast/Toast.stories.ts
  src/stories/toast/index.styles.tsx
  src/stories/toast/index.tsx
Labels: ✨ Feature

#65 [FEAT] 검색 페이지 구현
  src/assets/icons/back_button_red.svg
  src/assets/icons/closeButton.svg
  src/assets/icons/filter.svg
  src/assets/icons/filter_active.svg
  src/assets/icons/filter_mini_active.svg
  src/assets/icons/time_icon.svg
  src/pages/edit/index.styles.tsx
  src/pages/edit/index.tsx
  src/pages/login/index.tsx
  src/pages/login/oauth.tsx
  src/pages/search/index.styles.tsx
  src/pages/search/index.tsx
  src/pages/signup/components/favorite-genre/index.styles.tsx
  src/pages/signup/components/favorite-movie/index.styles.tsx
  src/pages/signup/components/favorite-movie/index.tsx
  src/pages/signup/index.styles.tsx
  src/pages/signup/index.tsx
  src/routers/Router.tsx
Labels: ✨ Feature

#68 [FEAT] Picky Page Layout
  package.json
  src/components/genre/index.tsx
  src/mocks/browser.ts
  src/mocks/handlers/movie/playlist/index.ts
  src/pages/admin/operation/movie/movies/components/total-movies/index.tsx
  src/pages/picky/genre-detail/index.styles.tsx
  src/pages/picky/genre-detail/index.tsx
  src/pages/picky/main/components/best-movies/index.styles.tsx
  src/pages/picky/main/components/best-movies/index.tsx
  src/pages/picky/main/components/genres-tab/index.styles.tsx
  src/pages/picky/main/components/genres-tab/index.tsx
  src/pages/picky/main/components/movie-backdrop-banner/index.styles.tsx
  src/pages/picky/main/components/movie-backdrop-banner/index.tsx
  src/pages/picky/main/components/playlist/constants/index.tsx
  src/pages/picky/main/components/playlist/index.styles.tsx
  src/pages/picky/main/components/playlist/index.tsx
  src/pages/picky/main/index.styles.tsx
  src/pages/picky/main/index.tsx
  src/pages/signup/components/emoji/index.tsx
  src/routers/Router.tsx
  src/stories/genre-tab/GenreTab.stories.ts
  src/stories/genre-tab/index.styles.tsx
  src/stories/genre-tab/index.tsx
  src/stories/movie-item/index.styles.tsx
  src/stories/movie-item/index.tsx
  yarn.lock
Labels: ✨ Feature

#73 [FEAT] 개인 영화 추천 페이지 구현
  src/pages/recommendations/index.styles.tsx
  src/pages/recommendations/index.tsx
  src/routers/Router.tsx
Labels: ✨ Feature

#74 [FEAT] 마이페이지 프로필 UI 구현
  src/assets/icons/settings.svg
  src/assets/images/default_profile.png
  src/pages/edit/index.styles.tsx
  src/pages/edit/index.tsx
  src/pages/my/components/logout-modal/index.styles.tsx
  src/pages/my/components/logout-modal/index.tsx
  src/pages/my/index.styles.tsx
  src/pages/my/index.tsx
  src/routers/Router.tsx
  src/stories/button/index.styles.tsx
Labels: ✨ Feature

#75 [FEAT] 알림 페이지 레이아웃 설계
  src/pages/notification/components/notification-rander/index.styles.tsx
  src/pages/notification/components/notification-rander/index.tsx
  src/pages/notification/constants/index.tsx
  src/pages/notification/index.styles.tsx
  src/pages/notification/index.tsx
  src/routers/Router.tsx
Labels: ✨ Feature

#81 [FEAT] [FE] 마이페이지 팔로워/팔로잉 리스트 UI 구현
  src/assets/icons/critic_badge.svg
  src/pages/my/components/followers-modal/index.styles.tsx
  src/pages/my/components/followers-modal/index.tsx
  src/pages/my/components/logout-modal/index.tsx
  src/pages/my/index.styles.tsx
  src/pages/my/index.tsx
Labels: ✨ Feature

#87 [FEAT] 마이페이지 Tab Component 생성
  index.html
  src/assets/icons/PICKY 완성본.zip
  src/assets/icons/my-page/delete.svg
  src/assets/icons/my-page/empty-feed.svg
  src/assets/icons/my-page/empty-like.svg
  src/assets/icons/my-page/empty-review.svg
  src/assets/icons/my-page/feed.svg
  src/assets/icons/my-page/like.svg
  src/assets/icons/my-page/review.svg
  src/components/layout/index.tsx
  src/pages/movie-detail/components/movie-review/index.tsx
  src/pages/my/components/tab-menu/index.styles.tsx
  src/pages/my/components/tab-menu/index.tsx
  src/pages/my/components/tab-menu/like-movie/index.styles.tsx
  src/pages/my/components/tab-menu/like-movie/index.tsx
  src/pages/my/components/tab-menu/movie-log/index.styles.tsx
  src/pages/my/components/tab-menu/movie-log/index.tsx
  src/pages/my/components/tab-menu/review/index.styles.tsx
  src/pages/my/components/tab-menu/review/index.tsx
  src/pages/my/index.styles.tsx
  src/pages/my/index.tsx
  src/styles/global.ts
Labels: ✨ Feature

#92 [FIX] Routes Path 수정
  src/routers/Router.tsx
Labels: 🐞 BugFix

#95 [FEAT] 장르 아이콘 수정및 추가, 토스트 메세지 적용
  src/assets/images/adventure.png
  src/assets/images/crime.png
  src/assets/images/documentary.png
  src/assets/images/family.png
  src/assets/images/history.png
  src/assets/images/mystery.png
  src/assets/images/sf.png
  src/assets/images/tv.png
  src/assets/images/war.png
  src/assets/images/western.png
  src/pages/signup/components/birth-date/index.styles.ts
  src/pages/signup/components/birth-date/index.styles.tsx
  src/pages/signup/components/birth-date/index.tsx
  src/pages/signup/components/consent-form/index.tsx
  src/pages/signup/components/emoji/index.tsx
  src/pages/signup/components/favorite-genre/index.styles.tsx
  src/pages/signup/components/favorite-genre/index.tsx
  src/pages/signup/components/profile/index.tsx
  src/pages/signup/components/theme.ts
  src/pages/signup/components/ui.ts
  src/pages/signup/index.tsx
Labels: 🐞 BugFix

#98 [FIX] 2차 QA 마이페이지 모달창, 커서, 게시글 수정
  src/pages/movie-detail/index.tsx
  src/pages/my/components/logout-modal/index.styles.tsx
  src/pages/my/components/logout-modal/index.tsx
  src/pages/my/index.styles.tsx
  src/pages/my/index.tsx
  src/stories/button/index.styles.tsx
  src/stories/modal/index.styles.tsx
Labels: 🐞 BugFix

#103 [FIX] Error 페이지 NotFoundPage로 처리Up 124 fix/modify route path
  src/pages/not-found/index.styles.ts
  src/pages/not-found/index.tsx
  src/routers/Router.tsx
Labels: 🐞 BugFix

#110 [FEAT] Loading Component 추가
  package.json
  src/assets/lottie/loadingLottie.json
  src/components/loading/index.tsx
  src/pages/main/index.tsx
  yarn.lock
Labels: ✨ Feature

#112 [FEAT] 2차 QA 적용
  src/pages/login/oauth.tsx
  src/pages/signup/components/birth-date/index.tsx
  src/pages/signup/components/consent-form/index.tsx
  src/pages/signup/components/favorite-genre/index.styles.tsx
  src/pages/signup/components/favorite-genre/index.tsx
  src/pages/signup/components/favorite-movie/index.styles.ts
  src/pages/signup/components/favorite-movie/index.tsx
  src/pages/signup/components/gender/index.tsx
  src/pages/signup/components/nationality/index.tsx
  src/pages/signup/components/nick-name/index.tsx
  src/pages/signup/components/profile/index.tsx
  src/pages/signup/components/ui.ts
  src/pages/signup/components/user-name/index.styles.tsx
  src/pages/signup/components/user-name/index.tsx
  src/pages/signup/index.styles.tsx
  src/pages/signup/index.tsx
  src/pages/signup/utils/index.tsx
Labels: 🐞 BugFix

#113 Up 116 feat/login
  src/pages/signup/index.tsx
Labels: 🐞 BugFix

#114 [FIX] api 호출 주소 변경
  src/pages/login/oauth.tsx
  src/pages/signup/components/favorite-movie/index.tsx
  src/pages/signup/components/nick-name/index.tsx
  src/pages/signup/index.tsx
Labels: 🐞 BugFix

#115 fix: 경로 수정
  src/pages/login/oauth.tsx
Labels: 🐞 BugFix

#119 [FIX] 소셜 로그인 주소 변경
  src/pages/login/oauth.tsx
  src/pages/search/index.styles.tsx
  src/pages/signup/components/consent-form/index.styles.ts
  src/pages/signup/components/consent-form/index.tsx
  src/pages/signup/components/favorite-genre/index.tsx
  src/pages/signup/components/favorite-movie/index.tsx
  src/pages/signup/components/nick-name/index.tsx
  src/pages/signup/components/profile/index.styles.tsx
  src/pages/signup/components/profile/index.tsx
  src/pages/signup/index.tsx
  src/pages/social/edit/index.styles.ts
  src/pages/social/edit/index.tsx
Labels: 🐞 BugFix

#120 [FIX] API 호출 주소 변경
  src/pages/signup/components/favorite-movie/index.tsx
  src/pages/signup/components/nick-name/index.tsx
  src/pages/signup/index.tsx
Labels: 🐞 BugFix

#122 Up 131 feat/create mocking object
  src/mocks/handlers/review/index.ts
  src/pages/main/index.tsx
  src/pages/signup/components/favorite-movie/index.tsx
  src/pages/signup/index.tsx
Labels: 🐞 BugFix, ✨ Feature

#130 [ FIX] 2차 QA 수정
  src/pages/edit/index.styles.ts
  src/pages/edit/index.tsx
  src/pages/search/index.styles.tsx
  src/pages/signup/components/favorite-genre/index.tsx
  src/pages/signup/components/profile/index.styles.tsx
  src/pages/signup/components/profile/index.tsx
Labels: 🐞 BugFix

#131 [FIX] 회원가입 페이지 & 개인 프로필 수정 API 수정
  src/pages/edit/index.tsx
  src/pages/signup/index.tsx
  src/routers/Router.tsx
Labels: 🐞 BugFix

#137 [FEAT] Mocking Object 설계
  src/constants/json/board/board.json
  src/constants/json/board/board_comments.json
  src/constants/json/board/board_contents.json
  src/constants/json/board/board_likes.json
  src/constants/json/genres.json
  src/constants/json/movie.json
  src/constants/json/review.json
  src/constants/json/user.json
  src/mocks/browser.ts
  src/mocks/handlers/auth/index.ts
  src/mocks/handlers/board/index.ts
  src/mocks/handlers/board/responseData.json
  src/mocks/handlers/movie/genre/index.ts
  src/mocks/handlers/review/index.ts
  src/pages/login/index.tsx
  src/pages/main/index.tsx
  src/pages/my/index.tsx
Labels: ✨ Feature

#139 [FEAT] Mocking Object 일부 설계
  src/constants/json/board/board_comments.json
  src/mocks/handlers/board/index.ts
  src/pages/main/index.tsx
Labels: ✨ Feature

#140 [FEAT] 한줄평 POST API 연동
  src/pages/login/index.tsx
  src/pages/movie-detail/components/movie-review/index.tsx
  src/pages/movie-detail/reviews/components/review-graph/index.tsx
  src/pages/movie-detail/reviews/components/review-regist/index.tsx
  src/pages/movie-detail/reviews/index.tsx
Labels: ✨ Feature

#143 [FIX] my profile 요청 API 수정
  src/api/constants.ts
  src/assets/icons/picky_main_logo.svg
  src/pages/edit/index.tsx
  src/pages/login/google/oauth.tsx
  src/pages/login/kakao/oauth.tsx
  src/pages/login/naver/oauth.tsx
  src/routers/Router.tsx
Labels: 🐞 BugFix

#148 [FIX] edit 페이지 로그 추가
  src/api/constants.ts
  src/pages/edit/index.tsx
Labels: 🐞 BugFix

#146 [FEAT] Mocking Object 일부 설계
  src/constants/json/genres/genres.json
  src/constants/json/genres/movieAndGenre.json
  src/constants/json/movie/filmCrew.json
  src/constants/json/movie/movie.json
  src/constants/json/movie/movieBehindVideos.json
  src/constants/json/movie/movieCrew.json
  src/constants/json/movie/movieLikes.json
  src/constants/json/movie/platforms.json
  src/constants/json/user/genrePreferences.json
  src/mocks/browser.ts
  src/mocks/handlers/board/responseData.json
  src/mocks/handlers/movie/genre/index.ts
  src/mocks/handlers/movie/index.ts
  src/pages/main/index.tsx
Labels: 🐞 BugFix, ✨ Feature

#150 [UPDATE] env 파일 추천
  .github/workflows/main.yml
Labels: 🐞 BugFix

#151 [FIX] 구글 소셜 로그인 리다이렉트 주소 변경
  src/api/constants.ts
Labels: 🐞 BugFix

#153 [FEAT] Movie Controller API Mocking Object 설계 완료
  src/components/genre/index.tsx
  src/mocks/browser.ts
  src/mocks/handlers/movie/index.ts
  src/mocks/handlers/user/index.tsx
  src/pages/main/components/genres-movie/index.tsx
  src/pages/main/index.tsx
  src/pages/picky/genre-detail/index.tsx
  src/recoil/selectors/genresSelector.tsx
Labels: 🐞 BugFix, ✨ Feature

#154 [FIX]Update main.yml
  .github/workflows/main.yml
Labels: 🐞 BugFix

#155 [FIX] 게시물 좋아요 취소, 추가 하나 Controller에서 해결
  src/mocks/handlers/board/index.ts
  src/pages/main/index.tsx
Labels: 🐞 BugFix, ✨ Feature

#156 [FIX] 카카오톡 API 로그인 url 수정
  src/api/constants.ts
  src/pages/login/naver/oauth.tsx
Labels: 🐞 BugFix

#157 [FEAT] 추천 페이지 API 연결
  src/pages/edit/index.tsx
  src/pages/recommendations/index.tsx
Labels: 🐞 BugFix

#158 [FIX] 영화 추천 페이지 API 수정
  src/pages/recommendations/index.tsx
Labels: 🐞 BugFix

#159 [FEAT] 영화상세페이지 영화 정보 GET API 연동
  src/constants/json/movie/movie.json
  src/mocks/handlers/movie/index.ts
  src/mocks/handlers/review/resposneData.json
  src/pages/movie-detail/components/movie-info/index.tsx
  src/pages/movie-detail/components/movie-poster/index.tsx
  src/pages/movie-detail/components/movie-rating/index.styles.tsx
  src/pages/movie-detail/components/movie-rating/index.tsx
  src/pages/movie-detail/index.tsx
  src/pages/movie-detail/reviews/index.tsx
Labels: ✨ Feature

#162 [FIX] 추천 페이지 수정
  src/pages/recommendations/index.tsx
Labels: 🐞 BugFix

#163 [FIX] 영화 추천 페이지 수정
  src/pages/recommendations/index.tsx
Labels: 🐞 BugFix

#164 [FIX] 영화 추천 페이지 수정
  src/pages/recommendations/index.tsx
Labels: 🐞 BugFix

#165 [FIX] 영화 추천 페이지
  src/pages/recommendations/index.styles.tsx
  src/pages/recommendations/index.tsx
Labels: 🐞 BugFix

#167 [FIX] 영화 추천 페이지 수정 및 스토리북 수정
  src/pages/recommendations/index.tsx
  src/stories/movie-item/index.tsx
Labels: 🐞 BugFix

#168 [FIX] 영화 추천 페이지 수정
  src/stories/movie-item/index.tsx
Labels: 🐞 BugFix

#169 [
  src/pages/edit/index.tsx
  src/stories/movie-item/index.tsx
Labels: 🐞 BugFix

#171 [FIX] 유저 프로필 수정 페이지 수정
  src/pages/edit/index.tsx
Labels: 🐞 BugFix

#172 [FEAT] Mocking Object 일부 설계
  src/constants/json/line-review/lineReviewLikes.json
  src/constants/json/line-review/lineReviews.json
  src/mocks/handlers/review/index.ts
  src/pages/main/index.tsx
Labels: ✨ Feature

#173 [FIX] 장르 선택 버튼 전역 상태 관리
  src/components/genre/index.tsx
  src/pages/signup/components/favorite-genre/index.styles.ts
  src/pages/signup/components/favorite-genre/index.tsx
  src/pages/signup/index.tsx
  src/stories/genre-tab/index.styles.tsx
  src/stories/genre-tab/index.tsx
Labels: 🐞 BugFix

#175 [FEAT] 마이페이지 한줄평 api 연동 & 좋아요 api 연동
  src/assets/images/adBanner.jpg
  src/constants/json/line-review/lineReviews.json
  src/mocks/handlers/movie/index.ts
  src/mocks/handlers/review/index.ts
  src/pages/movie-detail/components/movie-info/index.styles.tsx
  src/pages/movie-detail/components/movie-rating/index.tsx
  src/pages/movie-detail/index.tsx
  src/pages/my/components/tab-menu/edit-review-modal/index.tsx
  src/pages/my/components/tab-menu/index.tsx
  src/pages/my/components/tab-menu/like-movie/index.styles.tsx
  src/pages/my/components/tab-menu/movie-log/index.styles.tsx
  src/pages/my/components/tab-menu/review/index.tsx
Labels: ✨ Feature

#178 [FIX] 회원가입 페이지 리펙토링 및 메인 로고 수정
  package.json
  src/pages/login/index.styles.tsx
  src/pages/login/index.tsx
  src/pages/signup/components/birth-date/index.tsx
  src/pages/signup/components/gender/index.tsx
  src/pages/signup/components/index.ts
  src/pages/signup/components/nationality/index.tsx
  src/pages/signup/index.styles.tsx
  src/pages/signup/index.tsx
  src/pages/signup/utils/index.tsx
  src/review/atoms.ts
  src/styles/ui.ts
  src/util/validator.ts
  yarn.lock
Labels: 🐞 BugFix

#183 [FIX] 회원가입 페이지 프로필 이미지 URL -> FormData로 전송
  src/pages/signup/components/profile/index.tsx
  src/pages/signup/index.tsx
  src/review/atoms.ts
  src/util/validator.ts
Labels: 🐞 BugFix

#185 [FEAT] 비하인드 모달창 YouTube API 연동 완료
  src/components/youtube-player/index.tsx
  src/constants/json/movie/movie.json
  src/constants/json/movie/movieBehindVideos.json
  src/mocks/handlers/review/index.ts
  src/pages/main/components/famous-movie/index.styles.tsx
  src/pages/main/components/famous-movie/index.tsx
  src/pages/movie-detail/components/behind-modal/index.styles.tsx
  src/pages/movie-detail/components/behind-modal/index.tsx
  src/pages/movie-detail/components/movie-rating/index.tsx
  src/pages/movie-detail/components/movie-review/index.styles.tsx
  src/pages/movie-detail/components/movie-review/index.tsx
  src/pages/movie-detail/index.tsx
  src/pages/my/components/tab-menu/edit-review-modal/index.tsx
  src/pages/my/components/tab-menu/review/index.tsx
Labels: ✨ Feature

#186 [FIX] 개인 프로필 수정 페이지에 이메일 내용 추가
  src/pages/edit/index.tsx
Labels: 🐞 BugFix

#190 [FIX] 마이페이지 한줄평 포스터 수정
  src/pages/my/components/tab-menu/review/index.tsx
Labels: 🐞 BugFix

#191 [FEAT] Up 131 feat/create mocking object
  src/components/layout/index.tsx
  src/components/navbar/index.tsx
  src/constants/routes/routeConfig.ts
  src/pages/admin/index.tsx
  src/pages/login/index.tsx
  src/pages/main/index.tsx
  src/pages/my/components/tab-menu/index.tsx
  src/pages/my/components/tab-menu/like-movie/index.styles.tsx
  src/pages/my/components/tab-menu/movie-log/index.styles.tsx
  src/recoil/atoms/isLoginState.ts
  src/recoil/selectors/useAuthorization.ts
  src/routers/AdminLayout.tsx
  src/routers/Router.tsx
  src/routers/router/AdminRoutes.tsx
  src/routers/router/GuestRoutes.tsx
  src/routers/router/ProtectedRoute.tsx
  src/routers/router/UserRoutes.tsx
Labels: 🐞 BugFix, ✨ Feature

#195 [FIX] 로그인 페이지 수정, 프로필 수정 페이지 수정
  src/pages/edit/index.tsx
  src/pages/login/naver/oauth.tsx
  src/pages/signup/components/user-name/index.tsx
  src/review/atoms.ts
Labels: 🐞 BugFix

#198 [FIX] 회원가입 페이지 버그 수정
  src/pages/signup/components/user-name/index.tsx
Labels: 🐞 BugFix

#200 [FIX] 소셜 로그인 받아오는 토큰 값들 쿠키에 저장
  package.json
  src/pages/login/index.tsx
  src/pages/login/naver/oauth.tsx
  yarn.lock
Labels: 🐞 BugFix

#209 fix: Merge branch 'dev' into UP-139-feat/signup-fix
  src/api/index.ts
  src/api/user/index.ts
  src/pages/signup/components/favorite-movie/index.tsx
Labels: 🐞 BugFix

#225 [FEAT] TOP 10 Movie && MSW Update && Social Login Update && SessionStorage -> Cookie Update
  src/components/navbar/index.tsx
  src/mocks/handlers/auth/index.ts
  src/mocks/handlers/board/index.ts
  src/mocks/handlers/movie/index.ts
  src/mocks/handlers/review/index.ts
  src/pages/login/naver/oauth.tsx
  src/pages/signup/index.tsx
  src/stories/movie-item/index.tsx
Labels: 🐞 BugFix, ✨ Feature

#227 [REFACTOR]회원가입 및 프로필 수정 데이터 전송 및 검증 로직 개선
  src/api/index.ts
  src/api/user/index.ts
  src/pages/edit/index.tsx
  src/pages/login/naver/oauth.tsx
  src/pages/signup/index.tsx
Labels: 🐞 BugFix

#228 [FIX]유저 정보 요청 로그 추가
  src/pages/edit/index.tsx
Labels: 🐞 BugFix

#230 [FIX] 프로필 수정 페이지 버그 수정
  src/pages/edit/index.tsx
  src/pages/login/naver/oauth.tsx
Labels: 🐞 BugFix

#234 fix: 구글 소셜 로그인
  src/pages/login/google/oauth.tsx
Labels: 🐞 BugFix

#236 [FEAT] 장르별 영화 1차 PR
  src/api/movie/index.ts
  src/components/genre/index.tsx
  src/constants/json/user.json
  src/hooks/movie/index.tsx
  src/mocks/handlers/movie/index.ts
  src/pages/main/components/famous-movie/index.tsx
  src/pages/main/components/genres-movie/index.tsx
  src/stories/movie-item/index.styles.tsx
  src/stories/movie-item/index.tsx
  src/types/api/movie/index.d.ts
Labels: 🐞 BugFix, ✨ Feature

#237 [FEAT] 영화상세페이지-영화정보조회 api 연동 1차 PR
  src/assets/icons/picky_mini.svg
  src/components/youtube-player/index.tsx
  src/constants/json/genres/genres.json
  src/mocks/browser.ts
  src/pages/movie-detail/components/behind-modal/index.tsx
  src/pages/movie-detail/components/movie-footer/index.styles.tsx
  src/pages/movie-detail/components/movie-footer/index.tsx
  src/pages/movie-detail/components/movie-info/index.tsx
  src/pages/movie-detail/components/movie-poster/index.styles.tsx
  src/pages/movie-detail/components/movie-poster/index.tsx
  src/pages/movie-detail/components/movie-rating/index.tsx
  src/pages/movie-detail/components/movie-review/index.tsx
  src/pages/movie-detail/components/share-modal/index.tsx
  src/pages/movie-detail/components/skeleton/index.tsx
  src/pages/movie-detail/global.d.ts
  src/pages/movie-detail/index.tsx
  src/pages/movie-detail/reviews/components/review-regist/index.tsx
  src/pages/movie-detail/reviews/index.styles.tsx
  src/pages/movie-detail/reviews/index.tsx
  src/pages/my/components/tab-menu/edit-review-modal/index.tsx
  src/pages/my/components/tab-menu/review/index.styles.tsx
  src/pages/my/components/tab-menu/review/index.tsx
Labels: ✨ Feature

#242 Up 139 feat/signup fix
  src/pages/edit/index.tsx
Labels: 🐞 BugFix

#265 [FEAT] Picky page - Playlist 커서 기반 무한 스크롤링 적용
  src/api/playlist/index.ts
  src/constants/json/line-review/lineReviewLikes.json
  src/hooks/playlist/index.ts
  src/mocks/handlers/movie/index.ts
  src/mocks/handlers/movie/playlist/index.ts
  src/mocks/handlers/review/index.ts
  src/pages/login/index.tsx
  src/pages/picky/genre-detail/index.tsx
  src/pages/picky/main/components/best-movies/index.tsx
  src/pages/picky/main/components/movie-backdrop-banner/index.tsx
  src/pages/picky/main/components/playlist/index.styles.tsx
  src/pages/picky/main/components/playlist/index.tsx
  src/pages/picky/main/index.tsx
Labels: ✨ Feature

#269 [FIX] 쿠키 담는 정보 수정
  src/pages/login/google/oauth.tsx
  src/pages/login/kakao/oauth.tsx
  src/pages/login/naver/oauth.tsx
Labels: 🐞 BugFix

#270 [FEAT] 영화 등록 API 구성
  src/api/movie/index.ts
  src/api/playlist/index.ts
  src/components/header/index.tsx
  src/components/pages/admin/info/index.tsx
  src/constants/header/index.tsx
  src/constants/json/movie/platform.json
  src/constants/routes/routeConfig.ts
  src/hooks/movie/index.tsx
  src/mocks/handlers/movie/index.ts
  src/pages/admin/main/index.styles.tsx
  src/pages/admin/operation/movie/movies/components/register-section/index.styles.tsx
  src/pages/admin/operation/movie/movies/components/register-section/index.tsx
  src/pages/admin/operation/movie/movies/index.styles.tsx
  src/recoil/atoms/isLoginState.ts
  src/recoil/selectors/useAuthorization.ts
  src/stories/header/Header.stories.tsx
  src/stories/header/index.styles.tsx
  src/stories/header/index.tsx
Labels: ✨ Feature

#271 [FEAT] 한줄평 api 연동
  src/api/linereview/index.ts
  src/api/movie/index.ts
  src/hooks/review/index.ts
  src/mocks/handlers/movie/index.ts
  src/mocks/handlers/review/index.ts
  src/pages/movie-detail/components/movie-rating/index.tsx
  src/pages/movie-detail/components/movie-review/index.tsx
  src/pages/movie-detail/index.tsx
  src/pages/movie-detail/reviews/components/review-graph/index.tsx
  src/pages/movie-detail/reviews/components/review-regist/index.tsx
  src/pages/movie-detail/reviews/index.tsx
  src/pages/my/index.tsx
Labels: ✨ Feature

#274 [FIX] youtube data api 오류 수정 & 마이페이지 쿠키 제거 & 영화 상세페이지 SEO 오류 수정
  src/api/youtube/index.ts
  src/mocks/handlers/movie/index.ts
  src/pages/login/index.tsx
  src/pages/movie-detail/components/behind-modal/index.tsx
  src/pages/movie-detail/index.tsx
  src/pages/movie-detail/reviews/components/review-graph/index.tsx
  src/pages/movie-detail/reviews/index.tsx
  src/pages/my/index.tsx
Labels: 🐞 BugFix

#276 Feat/playlist api
  src/api/index.ts
  src/api/movie/index.ts
  src/hooks/movie/index.tsx
  src/mocks/handlers/auth/index.ts
  src/pages/admin/operation/movie/movies/components/register-section/index.styles.tsx
  src/pages/admin/operation/movie/movies/components/register-section/index.tsx
  src/pages/admin/operation/movie/movies/components/total-movies/component/genre-tab/index.styles.tsx
  src/pages/admin/operation/movie/movies/components/total-movies/component/genre-tab/index.tsx
  src/pages/admin/operation/movie/movies/components/total-movies/component/movie-card/index.styles.ts
  src/pages/admin/operation/movie/movies/components/total-movies/component/movie-card/index.tsx
  src/pages/admin/operation/movie/movies/components/total-movies/index.styles.tsx
  src/pages/admin/operation/movie/movies/components/total-movies/index.tsx
  src/stories/header/index.styles.tsx
  src/stories/header/index.tsx
  src/types/api/movie/index.d.ts
Labels: 🐞 BugFix, ✨ Feature

#275 [FIX] youtube data api 오류 수정 & 마이페이지 쿠키 제거 & 영화 상세페이지 SEO 오류 수정 2차 PR
  src/pages/movie-detail/components/behind-modal/index.tsx
  src/pages/movie-detail/reviews/index.tsx
Labels: 🐞 BugFix

#286 [FEAT] 마이페이지 api 연동 1차 PR
  src/api/linereview/index.ts
  src/api/movie/index.ts
  src/api/user/index.ts
  src/pages/movie-detail/reviews/components/review-regist/index.tsx
  src/pages/movie-detail/reviews/index.styles.tsx
  src/pages/my/components/tab-menu/edit-review-modal/index.tsx
  src/pages/my/components/tab-menu/index.tsx
  src/pages/my/components/tab-menu/like-movie/index.styles.tsx
  src/pages/my/components/tab-menu/like-movie/index.tsx
  src/pages/my/components/tab-menu/review/index.styles.tsx
  src/pages/my/components/tab-menu/review/index.tsx
  src/pages/my/index.tsx
Labels: ✨ Feature

#287 [FIX] 마이페이지 API 연동 코드 수정
  src/pages/my/index.tsx
Labels: 🐞 BugFix

#291 [FIX] 마이페이지 api 연동 4차 PR
  src/pages/my/components/tab-menu/review/index.tsx
Labels: 🐞 BugFix

#295 [FIX] 마이페이지 한줄평 api 연동 5차 PR
  src/api/linereview/index.ts
  src/pages/my/components/tab-menu/review/index.tsx
Labels: 🐞 BugFix

#297 [FEAT] Admin PlayList 페이지 API 연결 및 생성, 수정, 삭제
  src/api/playlist/index.ts
  src/pages/admin/operation/movie/playlists/index.tsx
Labels: 🐞 BugFix

#298 [FEAT] 검색 페이지 API 연결 및 디자인 수정
  src/api/user/index.ts
  src/pages/search/index.styles.tsx
  src/pages/search/index.tsx
Labels: ✨ Feature

#300 Up 139 feat/signup fix
  src/pages/recommendations/index.styles.tsx
Labels: 🐞 BugFix

#307 [FEAT] 관리자 플레이 리스트 기능 추가
  src/api/playlist/index.ts
  src/pages/admin/operation/movie/playlists/index.tsx
Labels: 🐞 BugFix, ✨ Feature

#312 Feat/notification api
  README.md
  src/App.tsx
  src/api/index.ts
  src/api/notification/index.ts
  src/components/layout/index.tsx
  src/components/seo/index.tsx
  src/hooks/notification/connect/badge.ts
  src/hooks/notification/connect/index.ts
  src/hooks/notification/fetch-initial-notification/index.ts
  src/hooks/notification/fetch/index.ts
  src/pages/main/index.tsx
  src/pages/notification/components/notification-rander/index.styles.tsx
  src/pages/notification/components/notification-rander/index.tsx
  src/pages/notification/constants/index.tsx
  src/pages/notification/index.tsx
  src/recoil/atoms/isNotificationState.ts
  src/types/api/notification/index.d.ts
Labels: ✨ Feature

#323 [FEAT] 마이페이지 수정 모달창 확인 모달 추가
  src/pages/movie-detail/reviews/components/review-regist/index.tsx
  src/pages/movie-detail/reviews/index.tsx
  src/pages/my/components/logout-modal/index.tsx
  src/pages/my/components/tab-menu/edit-review-modal/index.styles.tsx
  src/pages/my/components/tab-menu/edit-review-modal/index.tsx
  src/stories/modal/index.styles.tsx
Labels: ✨ Feature

#326 [FIX] 사용자 정보 불러오는 API 버그 수정
  src/api/user/index.ts
Labels: 🐞 BugFix

#328 [FIX]회원 가입시 기본 이미지 설정을 했을경우 기본 이미지 formada로 서버에 전송
  src/pages/signup/components/favorite-movie/index.tsx
  src/pages/signup/components/profile/index.tsx
Labels: 🐞 BugFix

#337 feat: 프로필 수정 페이지에서 기본 이미지 설정할 경우 기본 이미지 파일 서버에 전송
  src/pages/signup/index.tsx
  src/util/validator.ts
Labels: 🐞 BugFix

#338 [FEAT] 마이페이지 프로필 & 팔로우/팔로잉 API 연동
  src/api/user/index.ts
  src/constants/json/user.json
  src/mocks/browser.ts
  src/mocks/handlers/auth/index.ts
  src/pages/login/index.tsx
  src/pages/movie-detail/index.styles.tsx
  src/pages/movie-detail/index.tsx
  src/pages/movie-detail/reviews/index.styles.tsx
  src/pages/movie-detail/reviews/index.tsx
  src/pages/my/components/followers-modal/index.styles.tsx
  src/pages/my/components/followers-modal/index.tsx
  src/pages/my/components/logout-modal/index.styles.tsx
  src/pages/my/components/logout-modal/index.tsx
  src/pages/my/index.styles.tsx
  src/pages/my/index.tsx
  src/stories/modal/index.styles.tsx
Labels: ✨ Feature

#341 [FEAT] 한줄평 좋아요/싫어요 & 한줄평 삭제 api 연동
  src/api/linereview/index.ts
  src/pages/movie-detail/components/movie-review/index.styles.tsx
  src/pages/movie-detail/components/movie-review/index.tsx
  src/pages/movie-detail/index.tsx
  src/pages/movie-detail/reviews/components/review-regist/index.tsx
  src/pages/movie-detail/reviews/index.tsx
  src/pages/my/components/tab-menu/review/index.styles.tsx
  src/pages/my/components/tab-menu/review/index.tsx
Labels: ✨ Feature

#358 [FIX] 검색 페이지 검색어 항상 소문자로 전송
  src/pages/search/index.tsx
Labels: 🐞 BugFix

#369 [FIX] 한줄평 등록 & 검색창 수정
  src/constants/json/user.json
  src/pages/login/index.tsx
  src/pages/movie-detail/components/movie-header/index.styles.tsx
  src/pages/movie-detail/components/movie-review/index.tsx
  src/pages/movie-detail/reviews/components/review-regist/index.styles.tsx
  src/pages/movie-detail/reviews/components/review-regist/index.tsx
  src/pages/movie-detail/reviews/index.tsx
  src/pages/search/index.styles.tsx
  src/pages/search/index.tsx
Labels: 🐞 BugFix

#375 feat: splash_screen
  src/App.tsx
  src/components/splash-screen/index.styles.tsx
  src/components/splash-screen/index.tsx
Labels: ✨ Feature
